""""
Open messenger.com

log-in to messenger

How do I go about scrolling up to pull the data? Can I do it live?

Possibly upload data to website?

Will probably take hours to scrape a single conversation by just scrolling, so going to have to find a way to easily
go through the html data provided by Facebook's data download page. Possibly create a UI where you can choose which
groups to analyze, and which queries to use on those groups. Should be able to select group (or search from list), list
will be generated by going through folder names.

"""

#  ask for file path of data file
from tkinter import Tk
from tkinter.filedialog import askopenfilename

Tk().withdraw()  # we don't want a full GUI, so keep the root window from appearing
filename = askopenfilename()  # show an "Open" dialog box and return the path to the selected file
print(filename)
